Params = {
    "standard": {
        "skip_lowq": 7,
        "p5_sense": "TCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCTGGG",
        "p3_sense": "A{100}GAAGATAGAGCGACAGGCAAGTCACAAAGACACCGACAAC",
        "poly_w": 6,
        "poly_k": 4,
        "filter_short": 1,
        "trim_adapter": True,
        "trim_poly": True,
        "orientation": 1,
        "report": "report.json",
        "processes": 16,
        "beta": .5
    },
    "annotate": {
        "p5_sense": "TCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCTGGG",
        "p3_sense": "A{100}GAAGATAGAGCGACAGGCAAGTCACAAAGACACCGACAAC",
        "isl5": [0, 130],
        "isl3": [-60, -1],
        "pid5": 0.7,
        "pid3": 0.7,
        "pid_body": 0.7,
        "poly_w": 6,
        "poly_k": 4,
        "orientation": 0,
        "output_full_length": "-",
        "output_fusion": "-",
        "output_truncated": "-",
        "report": "report.json",
        "processes": 16,
        "beta": .5
    },
    "report": {
        "disable_annot": True,
        "report": "report.json"
    }
}
Defaults = {
    "input_fq": None,
    "mode": None,
    "config": None,
    "report": None,
    "processes": 1,
    "batch_size": 1000000,
    "seed": 42,
    "n": 100000,
    "beta": None,
    "disable_annot": False,
    "skip_lowq": -1,
    "skip_short": -1,
    "p5_sense": None,
    "p3_sense": None,
    "isl5": None,
    "isl3": None,
    "pid5": None,
    "pid3": None,
    "pid_body": None,
    "poly_w": None,
    "poly_k": None,
    "trim_adapter": False,
    "trim_poly": False,
    "filter_short": -1,
    "filter_lowq": -1,
    "orientation": 0,
    "output_fusion": None,
    "output_truncated": None,
    "output_full_length": None,
    "suffix_filtered": None,
}
